// Generated by CoffeeScript 1.6.3
(function() {
  var webdriver;

  webdriver = require('selenium-webdriver');

  module.exports = function(pages, repeat, delay, startDelay) {
    var driver, loadPage, _pages;
    if (repeat == null) {
      repeat = true;
    }
    if (delay == null) {
      delay = 15;
    }
    if (startDelay == null) {
      startDelay = delay * 100;
    }
    if ((pages == null) || pages.length === 0) {
      return;
    }
    _pages = pages.slice();
    console.log("Loading driver...");
    driver = new webdriver.Builder().withCapabilities(webdriver.Capabilities.firefox()).build();
    driver.manage().timeouts().setScriptTimeout(3 * 60 * 1000);
    loadPage = function(page) {
      console.log("Navigating to " + page + "...");
      return driver.get(page).then(function() {
        console.log("Auto-scrolling...");
        return driver.executeAsyncScript("var cb = arguments[arguments.length - 1];\nfunction pageScroll() {\n    window.scrollBy(0,1);\n    if (document.documentElement.scrollTop == document.documentElement.scrollTopMax)\n      cb();\n    else\n      scrolldelay = setTimeout(pageScroll," + delay + ");\n}\nsetTimeout(pageScroll," + startDelay + ");").then(function() {
          var p;
          p = _pages.shift();
          if (p != null) {
            return loadPage(p);
          } else {
            if (repeat) {
              console.log("\nRepeating...");
              _pages = pages.slice();
              return loadPage(_pages.shift());
            } else {
              return driver.quit();
            }
          }
        });
      });
    };
    return loadPage(_pages.shift());
  };

}).call(this);
